name: logimap
description: A Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0

  # 🔔 Bildirimler
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.0.0

  # 📍 Harita + konum
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^12.0.0

  # 🔗 Link / yol tarifi
  url_launcher: ^6.3.0

  # 🔥 Firebase
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.3.6

  # 🖼️ Fotoğraf seçme
  image_picker: ^1.1.2

  # 📝 Dijital İrsaliye (e-CMR) ve İmza
  signature: ^5.4.0
  pdf: ^3.11.0
  printing: ^5.11.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/logo.png

# 🟢 İKON AYARLARI 🟢
flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/icon.png"

  # Logonun arka planındaki o koyu lacivert rengi buraya yazdık.
  # Android bu rengi alıp, yuvarlak çerçevenin içindeki beyazlıkları dolduracak.
  adaptive_icon_background: "#040E27"

  # Logonun kendisini de ön plana (merkeze) koyuyoruz.
  adaptive_icon_foreground: "assets/icon.png"